
server:
  port: 8081

spring:
  application:
    name: cities-service
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/cities_service?serverTimeZone=UTC
    username: root
    password: ''

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
