spring:
  application:
    name: eureka-server
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_REPO_URI}
  profiles:
    active: native

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

  instance:
    lease-renewal-interval-in-seconds: 0
