server:
  port: 8083

spring:
  application:
    name: hotels-service
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/hotels_service
    username: root
    password: ''

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
